name: cella_eco
description: Monorepo helpers including syncing contributors and testing.
repository: https://github.com/cellawiki/open/tree/main/cella-lints
version: 0.0.0
resolution: workspace
environment: {sdk: ^3.6.0}

dependencies:
  # Introduce cella_lints here to use its colorful formatter,
  # because the logger cella_log package will use current repo.
  cella_lints: ^0.1.2
  path: ^1.9.1
  yaml: ^3.1.3
  yaml_edit: ^2.2.2

dev_dependencies:
  test: ^1.25.14
