name: cella_lints
description: Shared linter options and the tool to sync from the Docs.
version: 1.0.0
resolution: workspace
publish_to: none
environment: {sdk: ^3.6.0}

dependencies:
  html: ^0.15.5
  http: ^1.2.2
  path: ^1.9.1
  yaml: ^3.1.3
  yaml_edit: ^2.2.2

dev_dependencies:
  test: ^1.25.14
