name: cella_lints
description: Shared linter options and the sync tool from API docs behind it.
repository: https://github.com/cellawiki/open/tree/main/cella-lints
version: 0.1.2
resolution: workspace
environment: {sdk: ^3.6.0}

dependencies:
  html: ^0.15.5
  http: ^1.2.2
  path: ^1.9.1
  yaml: ^3.1.3
  yaml_edit: ^2.2.2

dev_dependencies:
  test: ^1.25.14
